### ISSUE TITLE
Not able to add your plugin in my ionic project

### ISSUE THREAD

**Issue by tanaji710** [iampossible/Cordova-DocPicker#3]
i am trying to add your plugin in my ionic app but not able to add it showing following error

Adding cordova-plugin-documentpicker to package.json
Saved plugin info for "cordova-plugin-documentpicker" to config.xml
(node:12480) UnhandledPromiseRejectionWarning: Error: Cannot find module '../cordova/platform_metadata'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Context.requireCordovaModule (C:\Users\prajakta\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\Context.js:77:12)
    at exports.default (C:\Users\prajakta\WebstormProjects\testing\vknktschoolapp_chinmay\plugins\cordova-plugin-add-swift-support\add-swift-support.js:12733:34)
    at runScriptViaModuleLoader (C:\Users\prajakta\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:188:18)
    at runScript (C:\Users\prajakta\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:164:16)
    at C:\Users\prajakta\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:132:20
    at _fulfilled (C:\Users\prajakta\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:787:54)
(node:12480) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a
 promise which was not handled with .catch(). (rejection id: 1)
(node:12480) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a
non-zero exit code.

**Comment by dumparun** [comment]
cordova plugin rm cordova-plugin-add-swift-support --force
cordova plugin add cordova-plugin-add-swift-support


Follow this link

https://stackoverflow.com/questions/48087357/cordova-8-ios-4-5-4-cannot-find-module-cordova-platform-metadata
